//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public int MerchantID { get; set; }
        public string MerchantName { get; set; }
        public string AddCategory { get; set; }
        public string AddItem { get; set; }
        public string RemoveItem { get; set; }
    }
}
